### ISSUE TITLE
Fully don't work with ElectronAPI.

### ISSUE THREAD

**Issue by MairwunNx** [random-access-storage/random-access-file#17]
![image](https://user-images.githubusercontent.com/39625750/50839792-1de11300-1372-11e9-8d3a-f9850cc68ea5.png)

When try read file as: `console.log(file.read(551846, 4, 'err'))` it caused error.
Please, fix it, library good, but i don't can it use because it not work. Thanks for attention.

**Comment by canadaduane** [comment]
@pvh is using a fork of `random-access-file` for the "pushpin" app because of this issue. Since Electron imports libraries like a web browser does, `random-access-file` raises the "random-access-file is not supported in the browser" error even though it is supported and can be used in Electron.

See https://github.com/pvh/random-access-file/commit/4f88c0289b97fcc3e45c3917c2921de772375352

**Comment by canadaduane** [comment]
Ahh, just noticed PR #21

**Comment by mafintosh** [comment]
We use the --node flag to the bundler
